#!/bin/bash
FILES=/home/spence/Desktop/tensorflow-music-generator/out/*.midi
for f in $FILES
do
  echo "Converting $f to MP3..."
  timidity $f -Ow -o - | ffmpeg -i - -acodec libmp3lame -ab 64k $f.mp3
done
